# Generated by Django 3.2.7 on 2021-09-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='additional_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
