# Generated by Django 3.2.7 on 2021-09-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20210913_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='preview',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
