# Generated by Django 3.2.7 on 2021-10-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20210913_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='time_period',
        ),
    ]
