# Generated by Django 3.2.7 on 2021-09-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_site_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
