# Generated by Django 3.2.3 on 2021-10-15 02:29

from django.db import migrations, models
import django.db.models.deletion
import sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='site',
            name='serial_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('video', models.FileField(upload_to=sites.models.Videos.file_upload_location)),
                ('related_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('photo', models.FileField(upload_to=sites.models.Photos.file_upload_location)),
                ('related_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sites.site')),
            ],
        ),
    ]
